#ifndef EVOCODERCORE_GLOBAL_H
#define EVOCODERCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(EVOCODERCORE_LIBRARY)
#	define BioBlocksJSONReader Q_DECL_EXPORT
#	define ExecutionMachineServer Q_DECL_EXPORT
#	define ExecutionServer Q_DECL_EXPORT
#	define CommandSender Q_DECL_EXPORT
#	define CommunicationsInterface Q_DECL_EXPORT
#	define FileSender Q_DECL_EXPORT
#	define SerialSender Q_DECL_EXPORT
#	define Light Q_DECL_EXPORT
#	define Mixer Q_DECL_EXPORT
#	define ODSensor Q_DECL_EXPORT
#	define Temperature Q_DECL_EXPORT
#	define Instructable Q_DECL_EXPORT
#	define Control Q_DECL_EXPORT
#	define Extractor Q_DECL_EXPORT
#	define Injector Q_DECL_EXPORT
#	define BidirectionalSwitch Q_DECL_EXPORT
#	define ConvergentSwitch Q_DECL_EXPORT
#	define ConvergentSwitchInlet Q_DECL_EXPORT
#	define DivergentSwitch Q_DECL_EXPORT
#	define DivergentSwitchSink Q_DECL_EXPORT
#	define ExecutableContainerNode Q_DECL_EXPORT
#	define FlowContainer Q_DECL_EXPORT
#	define InletContainer Q_DECL_EXPORT
#	define SinkContainer Q_DECL_EXPORT
#	define ExecutableMachineGraph Q_DECL_EXPORT
#	define ExecutionEngine Q_DECL_EXPORT
#	define ContainerNode Q_DECL_EXPORT
#	define ContainerNodeType Q_DECL_EXPORT
#	define MachineGraph Q_DECL_EXPORT
#	define ContinuousFlowEngine Q_DECL_EXPORT
#	define Mapping Q_DECL_EXPORT
#	define MappingEngine Q_DECL_EXPORT
#	define IdSearcher Q_DECL_EXPORT
#	define PathManager Q_DECL_EXPORT
#	define PathSearcher Q_DECL_EXPORT
#	define PathSearcherIterator Q_DECL_EXPORT
#	define SearcherInterface Q_DECL_EXPORT
#	define SearcherIterator Q_DECL_EXPORT
#	define SimplePathSearcher Q_DECL_EXPORT
#	define TypeSearcher Q_DECL_EXPORT
#	define Edge Q_DECL_EXPORT
#	define Node Q_DECL_EXPORT
#	define BooleanComparison Q_DECL_EXPORT
#	define ComparisonOperable Q_DECL_EXPORT
#	define SimpleComparison Q_DECL_EXPORT
#	define Tautology Q_DECL_EXPORT
#	define ComparisonOperable Q_DECL_EXPORT
#	define ArithmeticOperation Q_DECL_EXPORT
#	define ConstantNumber Q_DECL_EXPORT
#	define MathematicOperable Q_DECL_EXPORT
#	define UnaryOperation Q_DECL_EXPORT
#	define VariableEntry Q_DECL_EXPORT
#	define VariableTable Q_DECL_EXPORT
#	define ControlPlugin Q_DECL_EXPORT
#	define ExtractorPlugin Q_DECL_EXPORT
#	define InjectorPlugin Q_DECL_EXPORT
#	define LightPlugin Q_DECL_EXPORT
#	define MixerPlugin Q_DECL_EXPORT
#	define ODSensorPlugin Q_DECL_EXPORT
#	define SelfConfiguringPlugin Q_DECL_EXPORT
#	define TemperaturePlugin Q_DECL_EXPORT
#	define PluginFileLoader Q_DECL_EXPORT
#	define PythonEnvironment Q_DECL_EXPORT
#	define ConditionEdge Q_DECL_EXPORT
#	define OperationNode Q_DECL_EXPORT
#	define AssignationOperation Q_DECL_EXPORT
#	define ApplyLight Q_DECL_EXPORT
#	define ApplyTemperature Q_DECL_EXPORT
#	define ContainerOperation Q_DECL_EXPORT
#	define GetVolume Q_DECL_EXPORT
#	define LoadContainerOperation Q_DECL_EXPORT
#	define MeasureOD Q_DECL_EXPORT
#	define Mix Q_DECL_EXPORT
#	define SetContinousFlow Q_DECL_EXPORT
#	define Stir Q_DECL_EXPORT
#	define TimeStep Q_DECL_EXPORT
#	define Transfer Q_DECL_EXPORT
#	define DivergeNode Q_DECL_EXPORT
#	define LoopNode Q_DECL_EXPORT
#	define ProtocolGraph Q_DECL_EXPORT
#	define AutoEnumerate Q_DECL_EXPORT
#	define ContainersUtils Q_DECL_EXPORT
#	define Utils Q_DECL_EXPORT
# else
#	define BioBlocksJSONReader Q_DECL_IMPORT
#	define ExecutionMachineServer Q_DECL_IMPORT
#	define ExecutionServer Q_DECL_IMPORT
#	define CommandSender Q_DECL_IMPORT
#	define CommunicationsInterface Q_DECL_IMPORT
#	define FileSender Q_DECL_IMPORT
#	define SerialSender Q_DECL_IMPORT
#	define Light Q_DECL_IMPORT
#	define Mixer Q_DECL_IMPORT
#	define ODSensor Q_DECL_IMPORT
#	define Temperature Q_DECL_IMPORT
#	define Instructable Q_DECL_IMPORT
#	define Control Q_DECL_IMPORT
#	define Extractor Q_DECL_IMPORT
#	define Injector Q_DECL_IMPORT
#	define BidirectionalSwitch Q_DECL_IMPORT
#	define ConvergentSwitch Q_DECL_IMPORT
#	define ConvergentSwitchInlet Q_DECL_IMPORT
#	define DivergentSwitch Q_DECL_IMPORT
#	define DivergentSwitchSink Q_DECL_IMPORT
#	define ExecutableContainerNode Q_DECL_IMPORT
#	define FlowContainer Q_DECL_IMPORT
#	define InletContainer Q_DECL_IMPORT
#	define SinkContainer Q_DECL_IMPORT
#	define ExecutableMachineGraph Q_DECL_IMPORT
#	define ExecutionEngine Q_DECL_IMPORT
#	define ContainerNode Q_DECL_IMPORT
#	define ContainerNodeType Q_DECL_IMPORT
#	define MachineGraph Q_DECL_IMPORT
#	define ContinuousFlowEngine Q_DECL_IMPORT
#	define Mapping Q_DECL_IMPORT
#	define MappingEngine Q_DECL_IMPORT
#	define IdSearcher Q_DECL_IMPORT
#	define PathManager Q_DECL_IMPORT
#	define PathSearcher Q_DECL_IMPORT
#	define PathSearcherIterator Q_DECL_IMPORT
#	define SearcherInterface Q_DECL_IMPORT
#	define SearcherIterator Q_DECL_IMPORT
#	define SimplePathSearcher Q_DECL_IMPORT
#	define TypeSearcher Q_DECL_IMPORT
#	define Edge Q_DECL_IMPORT
#	define Node Q_DECL_IMPORT
#	define BooleanComparison Q_DECL_IMPORT
#	define ComparisonOperable Q_DECL_IMPORT
#	define SimpleComparison Q_DECL_IMPORT
#	define Tautology Q_DECL_IMPORT
#	define ComparisonOperable Q_DECL_IMPORT
#	define ArithmeticOperation Q_DECL_IMPORT
#	define ConstantNumber Q_DECL_IMPORT
#	define MathematicOperable Q_DECL_IMPORT
#	define UnaryOperation Q_DECL_IMPORT
#	define VariableEntry Q_DECL_IMPORT
#	define VariableTable Q_DECL_IMPORT
#	define ControlPlugin Q_DECL_IMPORT
#	define ExtractorPlugin Q_DECL_IMPORT
#	define InjectorPlugin Q_DECL_IMPORT
#	define LightPlugin Q_DECL_IMPORT
#	define MixerPlugin Q_DECL_IMPORT
#	define ODSensorPlugin Q_DECL_IMPORT
#	define SelfConfiguringPlugin Q_DECL_IMPORT
#	define TemperaturePlugin Q_DECL_IMPORT
#	define PluginFileLoader Q_DECL_IMPORT
#	define PythonEnvironment Q_DECL_IMPORT
#	define ConditionEdge Q_DECL_IMPORT
#	define OperationNode Q_DECL_IMPORT
#	define AssignationOperation Q_DECL_IMPORT
#	define ApplyLight Q_DECL_IMPORT
#	define ApplyTemperature Q_DECL_IMPORT
#	define ContainerOperation Q_DECL_IMPORT
#	define GetVolume Q_DECL_IMPORT
#	define LoadContainerOperation Q_DECL_IMPORT
#	define MeasureOD Q_DECL_IMPORT
#	define Mix Q_DECL_IMPORT
#	define SetContinousFlow Q_DECL_IMPORT
#	define Stir Q_DECL_IMPORT
#	define TimeStep Q_DECL_IMPORT
#	define Transfer Q_DECL_IMPORT
#	define DivergeNode Q_DECL_IMPORT
#	define LoopNode Q_DECL_IMPORT
#	define ProtocolGraph Q_DECL_IMPORT
#	define AutoEnumerate Q_DECL_IMPORT
#	define ContainersUtils Q_DECL_IMPORT
#	define Utils Q_DECL_IMPORT
#endif

#endif // EVOCODERCORE_GLOBAL_H
